<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.aribaweb</groupId>
        <artifactId>aribaweb-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>aribaweb-awreload</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>org.aribaweb</groupId>
            <artifactId>aribaweb-util</artifactId>
        </dependency>
        <dependency>
            <groupId>org.aribaweb</groupId>
            <artifactId>aribaweb-expr</artifactId>
        </dependency>
        <dependency>
            <groupId>org.aribaweb</groupId>
            <artifactId>aribaweb-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.aribaweb</groupId>
            <artifactId>aribaweb-widgets</artifactId>
        </dependency>
        <dependency>
            <groupId>org.aribaweb</groupId>
            <artifactId>aribaweb-metaui</artifactId>
        </dependency>
        <dependency>
            <groupId>ext-lib</groupId>
            <artifactId>servlet-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ext-lib</groupId>
            <artifactId>log4j</artifactId>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>${project.basedir}</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>adaptor-jdk15/**</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
