apply plugin: 'groovy'
apply plugin: 'war'

dependencies {
    implementation project(':util')
    implementation project(':expr')
    implementation project(':aribaweb-core')
    implementation project(':widgets')
    implementation project(':metaui')
    implementation project(':metaui-jpa')
    implementation project(':groovyloader')

    implementation fileTree(dir: "${rootDir}/lib/ext-demo", include: ['*.jar', '*.zip'])
}

sourceSets {
    main {
        groovy {
            srcDirs = ['.']
            include 'app/**/*.java'
            include 'app/**/*.groovy'
            include 'busobj/**/*.java'
            include 'busobj/**/*.groovy'
            include 'components/**/*.java'
            include 'components/**/*.groovy'
            include 'gallery/**/*.java'
            include 'gallery/**/*.groovy'
            include 'mailclient/**/*.java'
            include 'mailclient/**/*.groovy'
            include 'masterdetail/**/*.java'
            include 'masterdetail/**/*.groovy'
            include 'search/**/*.java'
            include 'search/**/*.groovy'
            include 'youtube/**/*.java'
            include 'youtube/**/*.groovy'
        }
        java {
            srcDirs = []
        }
        resources {
            srcDirs = ['.']
            include '**/*.awl'
            include '**/*.htm'
            include '**/*.oss'
            include '**/*.awz'
            include '**/*.afr'
            include '**/*.csv'
            include '**/*.xml'
            include '**/*.properties'
            exclude 'build/**'
        }
    }
}

task generateWebXml(type: rootProject.EvaluateTemplateTask) {
    classpath = project(':aribaweb-core').sourceSets.main.runtimeClasspath
    templateFile = file("${rootDir}/tools/templates/web.xml")
    outputFile = file("${buildDir}/generated/resources/web.xml")
    templateProperties = [
        'servlet.name': 'Demo',
        'servlet.displayName': 'AribaWeb Showcase',
        'servlet.description': 'Demo application displaying UI component and MetaUI gallery',
        'servlet.class': 'ariba.ui.servletadaptor.AWDispatcherServlet',
        'app.name': 'AribaWeb',
        'servlet.init.onstartup': 'false'
    ]
}


task generateAribawebProperties(type: rootProject.EvaluateTemplateTask) {
    classpath = project(':aribaweb-core').sourceSets.main.runtimeClasspath
    templateFile = file("${rootDir}/tools/templates/aribaweb.properties")
    outputFile = file("${buildDir}/generated/resources/META-INF/aribaweb.properties")
    templateProperties = [
        'aw.useNamespaceFromPackage': 'ariba.ui.meta',
        'aw.appName': 'Demo',
        'aw.packagedResourceExtensions': 'awl,oss,csv,xml',
        'aw.dependsOn': 'ariba.groovyloader,ariba.metaui',
        'aw.namespaceIdentifier': 'x'
    ]
}

processResources {
    dependsOn generateAribawebProperties
    from("${buildDir}/generated/resources") {
        include 'META-INF/aribaweb.properties'
    }
    from("${rootDir}/tools/templates") {
        include 'log4j.properties'
        include 'c3p0.properties'
    }
    // Copy local docroot files (preserving relative path inside docroot)
    from('.') {
        include '**/*.gif'
        include '**/*.jpg'
        include '**/*.css'
        include '**/*.js'
        exclude 'resource/**'
        exclude 'build/**'
        into 'docroot'
    }
    from('resource/webserver') {
        exclude 'branding/**'
        into 'docroot'
    }
    from('resource/webserver/branding') {
        into 'docroot/config/branding'
    }
}

war {
    dependsOn generateWebXml
    webXml = file("${buildDir}/generated/resources/web.xml")
}
