plugins {
    id 'war'
    id 'groovy'
}

description = 'AribaWeb Widget Gallery and Demo App'

dependencies {
    implementation project(':widgets')
    implementation project(':metaui')
    implementation project(':groovyloader')
    implementation project(':examples:appcore')

    implementation files("${rootProject.projectDir}/lib/ext/groovy-all.jar")
    implementation fileTree(dir: "${rootProject.projectDir}/lib/ext-demo", include: ['*.jar'])
    
    compileOnly files("${rootProject.projectDir}/lib/ext-build/javax.servlet.zip")
}

sourceSets {
    main {
        groovy {
            srcDirs = ['.']
            exclude 'build/**'
        }
        java {
            srcDirs = [] // Empty because Groovy joint compiles Java files in groovy.srcDirs
        }
        resources {
            srcDirs = ['.']
            include '**/*.awl', '**/*.properties', '**/*.xml', '**/*.png', '**/*.jpg', '**/*.gif', '**/*.js', '**/*.css'
            exclude 'build/**'
        }
    }
}

// Copy all JS files to classes/docroot
processResources {
    from('.') {
        include '**/*.js'
        exclude 'build/**'
        into 'docroot'
    }
}

war {
    archiveFileName = 'Demo.war'
}
