dependencies {
    implementation project(':util')
    implementation project(':expr')
    implementation project(':aribaweb-core')
    implementation project(':widgets')
    implementation project(':metaui')

    implementation fileTree(dir: "${rootDir}/lib/ext-jpa", include: ['*.jar', '*.zip'], exclude: ['javassist-*.jar'])
    implementation 'org.javassist:javassist:3.29.2-GA'
    implementation fileTree(dir: "${rootDir}/lib/ext-compass", include: ['*.jar', '*.zip'])
}

sourceSets {
    main {
        java {
            exclude 'examples/**'
        }
        resources {
            exclude 'examples/**'
        }
    }
}
